Algoritmo "Operadores Relacionais"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/01/2023
Var
// Seção de Declarações das variáveis 
 nota01, nota02: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota01:= 10
   nota02:= 15
   
   se(nota01 >= nota02) entao
   escreval("Nota 1 é diferente")
   senao
   escreval("Nota 1 é igual")
   fimse

Fimalgoritmo